version: '1.0'
stages:
  - setup
  - build
  - finalise
steps:
  main_clone:
    title: Cloning main repository...
    stage: 'setup'
    type: git-clone
    git: github
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"

  SetProperties:
    title: Setup build
    stage: 'setup'
    image: alpine/git
    commands:
      - cf_export GPG_IMPORT_COMMAND="cat <(echo -e '${{GPG_PRIVATE_KEY}}') | gpg --batch --import" --mask

  MvnSettings:
    stage: 'setup'
    title: Setup Maven settings
    image: alpine/git
    commands:
      - cf_export MVN_CLI_OPT="-Dmaven.repo.local=\"${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}_m2/repository\""

  ReleaseProperties:
    title: Setup release build
    stage: 'setup'
    image: alpine/git
    when:
      condition:
        all:
          releaseNameNotDefined: "${{TAG_REPO}} == true"
    commands:
      - cf_export RELEASE_NAME=${{TAG_NAME}}

  SnapshotProperties:
    title: Setup snapshot build
    stage: 'setup'
    image: alpine/git
    when:
      condition:
        all:
          releaseNameNotDefined: "${{TAG_REPO}} == false"
    commands:
      - cf_export RELEASE_NAME=${{GLOBAL_RELEASE_VERSION}}.${{CF_BRANCH_TAG_NORMALIZED}}-SNAPSHOT

  Build:
    title: Maven build
    stage: 'build'
    fail_fast: false
    image: maven:3.8.5-openjdk-17
    working_directory: ./
    commands:
      - bash -c "${{GPG_IMPORT_COMMAND}}"
      - mvn ${{MVN_CLI_OPT}} versions:set -DnewVersion="${{RELEASE_NAME}}" -DallowSnapshots=true
      - export CI_DEPLOY_USERNAME="${{CI_DEPLOY_USERNAME}}"
      - export CI_DEPLOY_PASSWORD="${{CI_DEPLOY_PASSWORD}}"
      - export GPG_KEYNAME="${{GPG_KEYNAME}}"
      - export GPG_PASSPHRASE="${{GPG_PASSPHRASE}}"
      - mvn -s settings.xml -U -B ${{MVN_CLI_OPT}} clean deploy -P gpg

  NotifySlackOnFail:
    title: Trigger Slack dev channel notification if main build failed
    stage: 'finalise'
    image: codefresh/cli
    when:
      branch:
        only:
          - main
      steps:
        - name: Build
          on:
            - failure
    commands:
      - export SAFE_COMMIT_AUTHOR='${{CF_COMMIT_AUTHOR}}'
      - export COMMIT_AUTHOR=${SAFE_COMMIT_AUTHOR:-MissingAuthor}
      - export SAFE_REPO_NAME='${{CF_REPO_NAME}}'
      - export REPO_NAME=${SAFE_REPO_NAME:-NoRepo}
      - export SAFE_COMMIT_MESSAGE='${{CF_COMMIT_MESSAGE}}'
      - export COMMIT_MESSAGE=${SAFE_COMMIT_MESSAGE:-NoCommitMsg}
      - echo Author is $SAFE_COMMIT_AUTHOR and commit msg is $SAFE_COMMIT_MESSAGE and repo is $SAFE_REPO_NAME
      - echo After substitution author is $COMMIT_AUTHOR and commit msg is $COMMIT_MESSAGE and repo is $REPO_NAME
      - codefresh run slack-notifier -v REPO_NAME="${REPO_NAME}" -v COMMIT_AUTHOR="${COMMIT_AUTHOR}" -v COMMIT_MESSAGE="${COMMIT_MESSAGE}"  --detach

  FailPipeline:
    title: Fail pipeline if the Maven build failed
    stage: 'finalise'
    image: codefresh/cli
    when:
      steps:
        - name: Build
          on:
            - failure
    commands:
      - exit 1

  TagRepo:
    title: Tag git repo with release name
    stage: 'finalise'
    image: alpine/git
    when:
      condition:
        all:
          buildPassed: steps.Build.result == 'success'
          isRelease: "${{TAG_REPO}}"
    commands:
      - echo This is a release build, tag repos with release name [${{RELEASE_NAME}}]
      - git fetch --prune https://${{REGNOSYS_OPS}}:${{REGNOSYS_OPS_TOKEN}}@github.com/finos/${{CF_REPO_NAME}}.git "+refs/tags/*:refs/tags/*"
      - git tag ${{RELEASE_NAME}}
      - git push https://${{REGNOSYS_OPS}}:${{REGNOSYS_OPS_TOKEN}}@github.com/finos/${{CF_REPO_NAME}}.git ${{RELEASE_NAME}}

  StartNextBuild:
    title: Build Rune-testing if on main
    stage: 'finalise'
    image: codefresh/cli
    when:
      branch:
        only:
          - main
      condition:
        all:
          buildPassed: steps.Build.result == 'success'
          variableDefined: "${{TAG_REPO}} == false"
          skipNextBuild: "${{SKIP_NEXT_BUILD}} == false"
    commands:
      - codefresh run FINOS/rune-testing --branch main --trigger finos/rune-testing/push --detach
