package com.regnosys.rosetta.common.serialisation;

/*-
 * ==============
 * Rune Common
 * ==============
 * Copyright (C) 2018 - 2026 REGnosys
 * ==============
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ==============
 */

import com.regnosys.rosetta.common.transform.PipelineModel;
import com.regnosys.rosetta.common.util.DeprecationLogger;
import com.rosetta.model.lib.transform.Ingest;
import com.rosetta.model.lib.transform.Projection;
import com.rosetta.model.lib.transform.SerializationFormat;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Optional;

/**
 * Resolves which {@link TransformSerialization} applies to the input or output side of a transform
 * function, from the {@code @Ingest}/{@code @Projection} annotation the Rune code generator places on
 * the generated function class.
 * <p>
 * This is the pure <em>decision</em> half of transform serialization: it only reads annotations off an
 * already-loaded {@link Class} and returns a value object. It constructs no Jackson mapper and captures
 * no {@link ClassLoader} — construction happens behind a {@link TransformMapperFactory}, whose
 * implementation owns the classloader (on the classpath: {@link ClasspathTransformMapperFactory};
 * runtimes that isolate model classloaders implement their own).
 * <p>
 * Sides resolve independently: the input is serialized only for an {@code @Ingest} (translate) function,
 * the output only for a {@code @Projection} function. The non-serialized side of a transform — and any
 * function without transform annotations — resolves to empty, letting the caller fall back to a default
 * (typically plain JSON, see {@link TransformSerialization#DEFAULT_JSON}).
 */
public final class TransformSerializationResolver {

    private static final Logger LOGGER = LoggerFactory.getLogger(TransformSerializationResolver.class);

    private TransformSerializationResolver() {
    }

    /**
     * The serialization of the transform function's <b>input</b>, from its {@link Ingest} annotation.
     * Empty when the class carries no {@code @Ingest} — e.g. the plain-JSON input of a projection, an
     * {@code @Enrich} transform, or a non-transform function.
     */
    public static Optional<TransformSerialization> input(Class<?> functionClass) {
        if (functionClass == null) {
            return Optional.empty();
        }
        Ingest ingest = functionClass.getAnnotation(Ingest.class);
        if (ingest == null) {
            return Optional.empty();
        }
        return Optional.of(new TransformSerialization(ingest.format(), emptyToNull(ingest.configPath())));
    }

    /**
     * The serialization of the transform function's <b>output</b>, from its {@link Projection}
     * annotation. Empty when the class carries no {@code @Projection} — e.g. the plain-JSON output of a
     * translate, an {@code @Enrich} transform, or a non-transform function.
     */
    public static Optional<TransformSerialization> output(Class<?> functionClass) {
        if (functionClass == null) {
            return Optional.empty();
        }
        Projection projection = functionClass.getAnnotation(Projection.class);
        if (projection == null) {
            return Optional.empty();
        }
        return Optional.of(new TransformSerialization(projection.format(), emptyToNull(projection.configPath())));
    }

    /**
     * Input-side resolution with a legacy pipeline-config fallback: the {@code @Ingest} annotation wins;
     * the pipeline's {@code inputSerialisation} applies when the annotation is absent (a function
     * generated before transform annotations existed), and supplies the config file when the annotation
     * has the format but no config (a function generated before annotations carried a config path).
     *
     * @deprecated the pipeline serialisation config is deprecated; the annotation on the generated
     *         function is the source of truth. This overload exists only to keep models generated by a
     *         pre-annotation DSL working — remove the pipeline serialisation (or regenerate the model)
     *         and use {@link #input(Class)}.
     */
    @Deprecated
    public static Optional<TransformSerialization> input(Class<?> functionClass, PipelineModel.Serialisation legacySerialisation) {
        return inputWithFallback(functionClass, fromLegacy(legacySerialisation).orElse(null));
    }

    /**
     * Output-side resolution with a legacy pipeline-config fallback: the {@code @Projection} annotation
     * wins, with the same fallback/merge semantics as
     * {@link #input(Class, PipelineModel.Serialisation)}.
     *
     * @deprecated see {@link #input(Class, PipelineModel.Serialisation)}.
     */
    @Deprecated
    public static Optional<TransformSerialization> output(Class<?> functionClass, PipelineModel.Serialisation legacySerialisation) {
        return outputWithFallback(functionClass, fromLegacy(legacySerialisation).orElse(null));
    }

    /**
     * Input-side resolution with an externally-sourced legacy fallback (e.g. a persisted pipeline
     * definition), with the semantics of {@link #input(Class, PipelineModel.Serialisation)}.
     *
     * @deprecated see {@link #input(Class, PipelineModel.Serialisation)} — the fallback exists only for
     *         models generated before transform annotations (carried a config path).
     */
    @Deprecated
    public static Optional<TransformSerialization> inputWithFallback(Class<?> functionClass, TransformSerialization legacyFallback) {
        return resolveWithLegacyFallback(input(functionClass), legacyFallback, functionClass, "input");
    }

    /**
     * Output-side resolution with an externally-sourced legacy fallback.
     *
     * @deprecated see {@link #inputWithFallback(Class, TransformSerialization)}.
     */
    @Deprecated
    public static Optional<TransformSerialization> outputWithFallback(Class<?> functionClass, TransformSerialization legacyFallback) {
        return resolveWithLegacyFallback(output(functionClass), legacyFallback, functionClass, "output");
    }

    private static Optional<TransformSerialization> resolveWithLegacyFallback(
            Optional<TransformSerialization> fromAnnotation,
            TransformSerialization legacy,
            Class<?> functionClass,
            String side) {
        if (fromAnnotation.isPresent()) {
            TransformSerialization annotation = fromAnnotation.get();
            // A model generated before annotations carried a config path may declare the format on the
            // annotation but ship the config file only in the deprecated pipeline serialisation. The
            // annotation still decides the format; merge in the legacy config rather than losing it.
            if (annotation.getConfigPath() == null
                    && legacy != null
                    && legacy.getFormat() == annotation.getFormat()
                    && legacy.getConfigPath() != null) {
                warnLegacyUse(functionClass, side, "config file");
                return Optional.of(new TransformSerialization(annotation.getFormat(), legacy.getConfigPath()));
            }
            return fromAnnotation;
        }
        if (legacy != null) {
            warnLegacyUse(functionClass, side, "serialization");
        }
        return Optional.ofNullable(legacy);
    }

    /** Warn once per function+side: this pipeline still relies on the deprecated serialisation config. */
    private static void warnLegacyUse(Class<?> functionClass, String side, String what) {
        String function = functionClass != null ? functionClass.getName() : "<unknown function>";
        DeprecationLogger.warnOnce(LOGGER, "legacy-serialisation:" + side + ":" + function,
                "The {} {} of transform function {} is driven by the deprecated pipeline "
                        + "serialisation config. Regenerate the model with a DSL that emits @Ingest/@Projection "
                        + "annotations (with a config path) and remove the pipeline's serialisation section.",
                side, what, function);
    }

    /**
     * Converts the deprecated pipeline-JSON serialisation into a {@link TransformSerialization}. Empty
     * when it is null or has no format. The two format enums share their constant names.
     */
    @SuppressWarnings("deprecation")
    private static Optional<TransformSerialization> fromLegacy(PipelineModel.Serialisation serialisation) {
        if (serialisation == null || serialisation.getFormat() == null) {
            return Optional.empty();
        }
        SerializationFormat format = SerializationFormat.valueOf(serialisation.getFormat().name());
        return Optional.of(new TransformSerialization(format, serialisation.getConfigPath()));
    }

    private static String emptyToNull(String configPath) {
        return configPath == null || configPath.isEmpty() ? null : configPath;
    }
}
